export enum MaskType {
  CPF = '###.###.###-##',
  CNPJ = '##.###.###/####-##',
  CEP = '#####-###',
  CARTAO = '#### #### #### ####',
  CEST = '##.###.##',
  CNS = '### #### #### ####',
  DATA = '##/##/####',
  HORA = '##:##',
  PLATE = '###-####',
  TEL_WITH_9 = '(##) #####-####',
  TEL = '(##) ####-####',
  TEL_WITH_9_NO_DDD = '####-####',
  TEL_NO_DDD = '#####-####',
  CERT_NASC = '###### ## ## #### # ##### ### ####### ##',
  VALIDADE_CARTAO1 = '##/##',
  VALIDADE_CARTAO2 = '##/####',
}
